# Project: 107062128_I2P_Project
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Users/Yazmau/Dev-Cpp/MinGW64/lib" -L"C:/Users/Yazmau/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/allegro-mingw-gcc6.2.0-x64-static-5.2.2/allegro/lib" C:/allegro-mingw-gcc6.2.0-x64-static-5.2.2/allegro/lib/liballegro_monolith.dll.a
INCS     = -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/include" -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/allegro-mingw-gcc6.2.0-x64-static-5.2.2/allegro/include"
CXXINCS  = -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/include" -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/Yazmau/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++" -I"C:/allegro-mingw-gcc6.2.0-x64-static-5.2.2/allegro/include"
BIN      = 107062128_I2P_Project.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
